import React, { useState, useEffect } from "react";
import { Loader, Card, FormField } from "../components";

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }
  return (
    <h2
      style={{
        marginTop: "1.25rem",
        fontWeight: "700",
        color: "#6469ff",
        fontSize: "1.25rem",
        textTransform: "uppercase",
      }}
    >
      {title}
    </h2>
  );
};
const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  const [searchText, setsearchText] = useState("");
  return (
    <section
      style={{
        maxWidth: "80rem",
        marginTop: "auto",
        marginBottom: "auto",
      }}
    >
      <div>
        <h1
          style={{
            fontStyle: "bold",
            color: "#222328",
            fontWeight: "900",
            fontSize: "25px",
          }}
        >
          The Community Showcase
        </h1>
        <p
          style={{
            marginTop: "0.5rem",
            color: "666e75",
            fontSize: "14px",
            maxWidth: "650px",
          }}
        >
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>
      <div style={{ marginTop: "4rem" }}>
        <FormField />
      </div>
      <div style={{ marginTop: "2.5rem" }}>
        {loading ? (
          <div
            style={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2
                style={{
                  fontSize: "24px",
                  color: "#666e75",
                  fontWeight: "500",
                  marginBottom: "1rem",
                }}
              >
                Showing results for&nbsp;
                <span style={{ color: "#222328" }}>{searchText}</span>
              </h2>
            )}
            <div
              style={{
                display: "grid",
                gap: "0.75rem",
                gridTemplateColumns: "repeat(2, 1fr)",
                "@media (min-width: 640px)": {
                  gridTemplateColumns: "repeat(3, 1fr)",
                },
                "@media (min-width: 1024px)": {
                  gridTemplateColumns: "repeat(4, 1fr)",
                },
              }}
            >
              {searchText ? (
                <RenderCards data={[]} title="No search result found" />
              ) : (
                <RenderCards data={[]} title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
